[package]
name = "cybernetic-trpg-playersheet"
version = "0.1.0"
edition = "2021"

[dependencies]
glib = "0.20.5"
gtk4 = "0.9.2"
non-empty-string = "0.2.5"
rfd = "0.15.0"
serde = "1.0.213"
serde_json = "1.0.132"
