[package]
name = "cybernetic-trpg-playersheet"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
iced_aw = "0.11.0"
non-empty-string = "0.2.5"
rfd = "0.15.0"
serde = "1.0.213"
serde_json = "1.0.132"
